# Generated by Django 6.1.1 on 2026-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrador de Sede'), ('supervisor', 'Supervisor'), ('operator', 'Operario')], default='operator', max_length=20),
        ),
    ]
