# Generated by Django 6.1.1 on 2026-09-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerCLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Código CLP')),
                ('lugar_produccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de Producción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clp_list', to='producers.producer', verbose_name='Productor')),
            ],
            options={
                'verbose_name': 'CLP de Productor',
                'verbose_name_plural': 'CLPs de Productores',
                'ordering': ['code'],
            },
        ),
    ]
