# Generated by Django 6.1.1 on 2026-09-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_producerclp'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='tenants.tenant', verbose_name='Sede'),
        ),
    ]
