# Generated by Django 6.1.1 on 2026-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_producer_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerclp',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito'),
        ),
    ]
