# Generated by Django 6.1.1 on 2026-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed roles for this tenant, e.g. ['admin', 'operator']"),
        ),
    ]
