# Generated by Django 6.1.1 on 2026-09-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_organization_tenant_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL del Logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL del Logo'),
        ),
    ]
