# Generated by Django 6.1.1 on 2026-09-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_organization_logo_organization_logo_url_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_units',
            field=models.BooleanField(default=False, help_text='Si está activo, muestra columnas, filtros y sufijos de unidades de medida (kg, etc.).', verbose_name='Mostrar Unidades'),
        ),
    ]
