# Generated by Django 6.1.1 on 2026-09-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_key', models.CharField(blank=True, default='', max_length=100, verbose_name='Clave Serial')),
                ('machine_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Identificador de Servidor')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('grace_period', 'En Gracia Offline'), ('suspended', 'Suspendida por Administración'), ('expired', 'Expirada'), ('revoked', 'Revocada'), ('unlicensed', 'Sin Licencia')], default='unlicensed', max_length=50, verbose_name='Estado')),
                ('customer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Cliente')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Heartbeat')),
                ('lease_until', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento del Lease')),
                ('grace_period_hours', models.IntegerField(default=48, verbose_name='Horas de Gracia Offline')),
                ('is_perpetual', models.BooleanField(default=False, help_text='Si está activo, el sistema opera indefinidamente sin requerir internet ni consultas al servidor.', verbose_name='Licencia Perpetua')),
                ('last_monotonic_timestamp', models.DateTimeField(blank=True, help_text='Evita la manipulación del reloj del sistema operativo.', null=True, verbose_name='Última Marca de Tiempo Registrada')),
                ('cached_token', models.TextField(blank=True, default='', verbose_name='Token de Lease Cifrado')),
                ('last_sync_error', models.TextField(blank=True, default='', verbose_name='Último Error de Sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Licencia',
                'verbose_name_plural': 'Estado de Licencia',
            },
        ),
    ]
