# Generated by Django 6.1.1 on 2026-09-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Variedad')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variedad de Producto',
                'verbose_name_plural': 'Variedades de Producto',
                'ordering': ['name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
