# Generated by Django 6.1.1 on 2026-09-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_varieties'),
        ('tenants', '0002_tenant_allowed_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'code')},
        ),
    ]
