# Generated by Django 6.1.1 on 2026-09-25 03:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_options_product_tenant_and_more'),
        ('tenants', '0005_tenant_show_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Campaña')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Campaña')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Cierre')),
                ('closed_summary', models.JSONField(blank=True, null=True, verbose_name='Resumen Consolidado de Cierre')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='inventory.product', verbose_name='Producto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'product'), name='unique_active_campaign_per_product_tenant')],
            },
        ),
    ]
