# Generated by Django 5.1.3 on 2025-05-16 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_product_68fce8_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_created_a6aabf_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_status_c732ef_idx',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='notes',
            new_name='datosGenerales_json',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='is_deleted',
            new_name='incrementLote',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='operator',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='report',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='report',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='report',
            name='product',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='tare_weight',
        ),
        migrations.AddField(
            model_name='report',
            name='registros_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='totalJabas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='totalPesoBruto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='totalPesoNeto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='totales_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('verified', 'Verificado'), ('cancelled', 'Cancelado')], default='completed', max_length=20),
        ),
    ]
