# Generated by Django 6.1.1 on 2026-09-25 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_campaign'),
        ('reports', '0004_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='inventory.campaign', verbose_name='Campaña'),
        ),
    ]
