# Generated by Django 6.1.1 on 2026-09-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='totalPesoBruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='totalPesoNeto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
